#!/bin/sh
set -e

case "$1" in
    remove|deconfigure)
       update-alternatives --remove desktop-background /usr/share/linaro/wallpapers/linaro-default-wallpaper.jpg
       ;;

    purge)
       ;;

    upgrade|failed-upgrade|disappear)
       ;;

    abort-install|abort-upgrade)
       ;;

    *)
       echo "$0 called with unknown argument \`$1'" 1>&2
       exit 1
       ;;
esac

#DEBHELPER#
exit 0
